version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@gpters-internal/ui"
    labels:
      - "auto-merge"
    open-pull-requests-limit: 5
